{{- $fullName := include "ingress.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-server
  labels:
    {{- include "ingress.labels" . | nindent 4 }}
spec:
  entryPoints: 
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ required "Missing hostName value" .Values.hostName }}`) && PathPrefix(`/api`)
    middlewares:
    {{- include "ingress.commonMiddlewares" . | nindent 4 }}
    - name: {{ $fullName }}-api-stripprefix
    services:
    - kind: Service
      name: {{ required "Missing serverHost value" .Values.serverHost }}
      port: http
  {{- include "ingress.tls" . | nindent 2 }}