{{- $fullName := include "ingress.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}-api-stripprefix
  labels:
    {{- include "ingress.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - /api